name: Deploy CURSOR Pipeline Demo to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: |
        # Создаем статическую версию для GitHub Pages
        mkdir -p dist
        cp -r public/* dist/
        
        # Создаем простой index.html для GitHub Pages
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="ru">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>CURSOR Pipeline Demo</title>
            <style>
                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    margin: 0;
                    padding: 20px;
                    min-height: 100vh;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }
                .container {
                    text-align: center;
                    color: white;
                    max-width: 800px;
                    background: rgba(255,255,255,0.1);
                    backdrop-filter: blur(10px);
                    border-radius: 20px;
                    padding: 40px;
                    box-shadow: 0 10px 30px rgba(0,0,0,0.2);
                }
                h1 { font-size: 3rem; margin-bottom: 20px; }
                .demo-badge {
                    background: linear-gradient(90deg, #ff6b6b, #ffa500);
                    padding: 10px 20px;
                    border-radius: 25px;
                    font-weight: bold;
                    display: inline-block;
                    margin: 20px 0;
                }
                .features {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                    gap: 20px;
                    margin: 30px 0;
                }
                .feature {
                    background: rgba(255,255,255,0.1);
                    padding: 20px;
                    border-radius: 10px;
                }
                .buttons {
                    margin-top: 30px;
                }
                .btn {
                    display: inline-block;
                    padding: 15px 30px;
                    margin: 10px;
                    background: linear-gradient(45deg, #ff6b6b, #ffa500);
                    color: white;
                    text-decoration: none;
                    border-radius: 8px;
                    font-weight: bold;
                    transition: transform 0.3s;
                }
                .btn:hover {
                    transform: translateY(-2px);
                }
                .warning {
                    background: rgba(255,193,7,0.2);
                    border: 1px solid rgba(255,193,7,0.5);
                    padding: 15px;
                    border-radius: 8px;
                    margin: 20px 0;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🚀 CURSOR Pipeline Demo</h1>
                <div class="demo-badge">ДЕМО-РЕЖИМ</div>
                
                <p>Система управления задачами и проектами</p>
                
                <div class="warning">
                    <strong>⚠️ Внимание:</strong> Это статическая демо-версия. 
                    Для полного функционала (Kanban доска, API, база данных) 
                    требуется серверная часть.
                </div>
                
                <div class="features">
                    <div class="feature">
                        <h3>📋 Управление задачами</h3>
                        <p>Kanban доска, цветовая маркировка, приоритеты</p>
                    </div>
                    <div class="feature">
                        <h3>👥 Команды и роли</h3>
                        <p>Исполнители, супервайзеры, руководители</p>
                    </div>
                    <div class="feature">
                        <h3>📊 Аналитика</h3>
                        <p>KPI метрики, загрузка сотрудников, отчеты</p>
                    </div>
                    <div class="feature">
                        <h3>🔔 Уведомления</h3>
                        <p>Сроки, просрочки, изменения статусов</p>
                    </div>
                </div>
                
                <div class="buttons">
                    <a href="https://github.com/jfsagro-glitch/zadachnik" class="btn">
                        📁 Исходный код
                    </a>
                    <a href="https://github.com/jfsagro-glitch/zadachnik/blob/main/README.md" class="btn">
                        📖 Документация
                    </a>
                </div>
                
                <div style="margin-top: 30px; font-size: 0.9em; opacity: 0.8;">
                    <p>Для полного функционала разверните проект локально или на сервере:</p>
                    <code style="background: rgba(0,0,0,0.3); padding: 10px; border-radius: 5px; display: block; margin: 10px 0;">
                        npm install && npm start
                    </code>
                </div>
            </div>
        </body>
        </html>
        EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
